# language `ghc` drags in old ghc versions
# language `generic` drags in too many others deps
# language `c` is lighter weight, and is fine since we declare most of our own deps
language: c

sudo: false

# cache only works if sudo is false
# this will attempt to cache the contents of the specified directories between
cache:
    directories:
        - $HOME/.cabal
        - $HOME/.ghc

# clean up anything we don't want to cache
# log and index files aren't worth caching
# Note: this should be safe as cabal should still do an install
#
#   if a newer version of a dependency is available
before_cache:
    - rm -f $HOME/.cabal/logs/*.log
    - rm -f $HOME/.cabal/packages/00-index*
    - rm -f $HOME/.cabal/packages/01-index*
    - rm -f $HOME/.cabal/packages/build-reports.log

# using ghc and cabal-install from
#   https://launchpad.net/~hvr/+archive/ubuntu/ghc
# llvm from
#   https://launchpad.net/~h-rayflood/+archive/ubuntu/llvm
#   https://launchpad.net/~h-rayflood/+archive/ubuntu/gcc-upper
#   https://launchpad.net/~h-rayflood/+archive/ubuntu/llvm-upper
addons:
    apt:
        sources:
            - sourceline: 'ppa:h-rayflood/llvm'
            - sourceline: 'ppa:h-rayflood/gcc-upper'
            - sourceline: 'ppa:h-rayflood/llvm-upper'
            - sourceline: 'ppa:hvr/ghc'
        packages:
            - llvm-3.5-dev
            - llvm-3.5-runtime
            - llvm-3.5
            - ghc-8.2.1
            - cabal-install-1.24

before_install:
    # put llvm-3.5 at the front of the path, ahead of any llvm-3.4
    - export PATH=/usr/lib/llvm-3.5/bin:$PATH
    # put ghc and cabal on the path
    - export PATH=/opt/ghc/8.2.1/bin:/opt/cabal/1.24/bin:$PATH
    - cabal update

# here we manually install all the needed deps
# by default travis would run `cabal install --only-dependencies --enable-tests`
# cabal install was unhappy when all deps were specified, so we install them
# one-by-one in the right order
install:
    - cabal install mtl parsec random stm text wl-pprint compact
    - cabal install buildbox inchworm

script:
    - make clean
    - make
    - make war

